sylius_twig_hooks:
    hooks:
        'sylius_admin.base#stylesheets':
            custom_styles:
                template: '@ThreeBRSSyliusPaymentFeePlugin/admin/shared/layout/base/styles.html.twig'
                priority: -100

        'sylius_admin.base#javascripts':
            custom_scripts:
                template: '@ThreeBRSSyliusPaymentFeePlugin/admin/_javascripts.html.twig'
                priority: -100

        sylius_admin.payment_method.create.content.form.sections:
            taxes:
                template: '@ThreeBRSSyliusPaymentFeePlugin/admin/PaymentMethod/Form/_form.html.twig'
                priority: 150 
